version: "3"

services:
  monitoring:
    build:
      context: monitoring
      dockerfile: Dockerfile
    container_name: monitoring-service
    volumes:
      - ./monitoring:/app
    command: python3 monitor.py

  ml_models:
    build:
      context: models_eval
      dockerfile: Dockerfile
    container_name: ml_models-service
    volumes:
      - ./models_eval:/app
    command: ./run.sh
